version: "3.8"
services:
    # PHP Service
    php:
        container_name: perks-app
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        command: /docker/entrypoint.sh
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker:/docker
        ports:
            - 8807:8807
        depends_on:
            - perks-db
        networks:
            - perks-net

    # Database Server
    perks-db:
        container_name: perks-db
        image: mysql:8.0
        command: --sort_buffer_size=50M
        ports:
            - 3317:3317
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - TZ=Asia/Shanghai
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - perks-net

        # PHPmyAdmin
    phpmyadmin:
        image: phpmyadmin:5.2.0-apache
        container_name: perks-phpmyadmin
        restart: unless-stopped
        tty: true
        ports:
            - 8107:80
        networks:
            - perks-net
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=10000M

networks:
    perks-net:
        driver: bridge

volumes:
    db-data: ~
